#define yy_create_buffer zz_create_buffer
#define yy_delete_buffer zz_delete_buffer
#define yy_scan_buffer zz_scan_buffer
#define yy_scan_string zz_scan_string
#define yy_scan_bytes zz_scan_bytes
#define yy_flex_debug zz_flex_debug
#define yy_init_buffer zz_init_buffer
#define yy_flush_buffer zz_flush_buffer
#define yy_load_buffer_state zz_load_buffer_state
#define yy_switch_to_buffer zz_switch_to_buffer
#define yyin zzin
#define yyleng zzleng
#define yylex zzlex
#define yyout zzout
#define yyrestart zzrestart
#define yytext zztext
#define yylineno zzlineno
#define yywrap zzwrap

#line 21 "asm-lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
static yyconst short int yy_acclist[365] =
    {   0,
        1,    1,  119,  117,  118,    1,  117,  118,    2,  118,
      117,  118,  114,  117,  118,   86,  117,  118,   86,  117,
      118,   89,  117,  118,  112,  117,  118,  117,  118,  117,
      118,  117,  118,  116,  117,  118,   87,  117,  118,   88,
      117,  118,   92,  112,  116,  117,  118,   93,  112,  116,
      117,  118,   94,  112,  116,  117,  118,   95,  112,  116,
      117,  118,   96,  112,  116,  117,  118,  112,  116,  117,
      118,   97,  116,  117,  118,  100,  116,  117,  118,  116,
      117,  118,   98,  116,  117,  118,   85,  116,  117,  118,
      116,  117,  118,  116,  117,  118,   84,  116,  117,  118,

       99,  116,  117,  118,  116,  117,  118,  116,  117,  118,
       80,  116,  117,  118,    1,  112,  113,    3,   90,   91,
      116,  112,  116,  112,  116,  111,  112,  116,  116,  105,
      112,  116,  116,  112,  116,  112,  116,  116,   18,  116,
      112,  116,  106,  112,  116,   22,  116,  116,   23,  116,
      116,   29,  116,  116,  116,  107,  116,   27,  116,   28,
      116,  109,  116,  110,  116,   30,  116,   31,  116,   34,
      116,   81,  116,  116,  116,   79,  116,   32,  116,  116,
      116,   83,  116,   82,  116,  116,  116,   39,  116,   40,
      116,  116,  116,  116,  116,  116,  108,  116,  116,  116,

      116,  115,   11,  112,  116,   12,  112,  116,   13,  116,
       14,  116,  116,   15,  112,  116,  116,   67,  116,   69,
      116,   16,  116,   19,  112,  116,   20,  112,  116,  112,
      116,  116,    6,  116,   25,  116,  116,  116,   21,  116,
       63,  116,   65,  116,  101,  116,  102,  116,  103,  116,
      104,  116,   57,  116,   59,  116,   61,  116,   62,  116,
        8,  116,  116,  116,   33,  116,   36,  116,  116,   37,
      116,   78,  116,   51,  116,   41,  116,   52,  116,   53,
      116,   42,  116,   55,  116,   75,  116,   48,  116,   56,
      116,   38,  116,   43,  116,   46,  116,   44,  116,   45,

      116,   49,  116,   47,  116,   17,  116,  116,   68,  116,
       70,  116,    4,  112,  116,    5,  116,   24,  116,    7,
      116,  116,   26,  116,   64,  116,   66,  116,   58,  116,
       60,  116,   72,  116,   71,  116,   74,  116,   73,  116,
       35,  116,   76,  116,   77,  116,   50,  116,   54,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,   10,
      116,  116,    9,  116
    } ;

static yyconst short int yy_accept[186] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   13,   16,   19,
       22,   25,   28,   30,   32,   34,   37,   40,   43,   48,
       53,   58,   63,   68,   72,   76,   80,   83,   87,   91,
       94,   97,  101,  105,  108,  111,  115,  116,  117,  118,
      118,  118,  119,  120,  121,  122,  124,  126,  129,  130,
      133,  134,  136,  138,  139,  141,  143,  146,  148,  149,
      151,  152,  154,  155,  156,  158,  160,  162,  164,  166,
      168,  170,  172,  174,  175,  176,  178,  180,  181,  182,
      184,  186,  187,  188,  190,  192,  193,  194,  195,  196,
      197,  199,  200,  201,  202,  203,  206,  209,  211,  213,

      214,  217,  218,  220,  222,  224,  227,  230,  232,  233,
      235,  237,  238,  239,  241,  243,  245,  247,  249,  251,
      253,  255,  257,  259,  261,  263,  264,  265,  267,  269,
      270,  272,  274,  276,  278,  280,  282,  284,  286,  288,
      290,  292,  294,  296,  298,  300,  302,  304,  306,  308,
      309,  311,  313,  316,  318,  320,  322,  323,  325,  327,
      329,  331,  333,  335,  337,  339,  341,  343,  345,  347,
      349,  351,  352,  353,  354,  355,  356,  357,  358,  359,
      360,  362,  363,  365,  365
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    6,    6,    7,    6,
        6,    6,    6,    6,    8,    1,    6,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    6,   10,   11,
        1,   12,    1,   13,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   13,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   13,   36,   37,   38,   39,
       14,    1,   15,    6,   13,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   25,   13,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   13,   36,   37,
       38,   39,    1,    6,    1,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    4,    1,    1,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst short int yy_base[189] =
    {   0,
        0,    0,  256,  257,  253,  257,    0,  245,  257,    0,
      257,    0,  250,  241,  239,    0,  257,  257,   31,   36,
       49,   64,   74,   32,   27,   34,   12,  231,    0,   58,
       69,   61,   74,   95,  220,    0,  246,    0,  238,  239,
      242,  257,  257,  257,    0,   85,  105,   89,  225,  110,
      209,  113,  116,  222,  121,  127,  131,    0,  213,    0,
      205,  202,  201,  211,    0,    0,  138,  128,  135,    0,
        0,   22,    0,  214,  205,    0,  212,   67,  199,    0,
      202,  198,   40,  147,  151,  196,  211,  207,  193,  102,
        0,  148,  209,  193,  257,  152,  156,    0,    0,  198,

      157,  207,  190,  189,    0,  160,  168,  173,  181,  195,
        0,  182,  173,    0,  174,  173,    0,    0,    0,    0,
      172,  171,    0,    0,    0,  170,  167,   95,    0,  175,
        0,  144,    0,  181,    0,    0,  179,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  154,
        0,    0,  172,    0,    0,    0,  167,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  156,  143,  137,  122,  119,   94,   79,   49,   40,
        0,   25,    0,  257,   42,  209,  213,  215
    } ;

static yyconst short int yy_def[189] =
    {   0,
      184,    1,  184,  184,  184,  184,  185,  184,  184,  186,
      184,  185,  187,  184,  184,  188,  184,  184,  188,   19,
       19,   19,   19,   23,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  184,  185,  184,  184,
      187,  184,  184,  184,  188,   23,   19,   19,  188,   19,
      188,   19,   19,  188,  188,   19,   19,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  184,   19,   19,  188,  188,  188,

       19,  188,  188,  188,  188,   19,   19,   19,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,   19,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,    0,  184,  184,  184,  184
    } ;

static yyconst short int yy_nxt[297] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   16,   25,   26,   27,   28,   29,   30,   31,   32,
       16,   33,   34,   16,   16,   16,   35,   16,   36,   46,
      121,   70,   64,   71,   38,  122,   46,   46,   46,   47,
       46,   48,   65,   50,   46,   63,   46,  183,   49,   51,
       66,   67,   45,   45,   52,  182,   53,   46,   45,   46,
       68,   69,  131,  132,   54,   73,   45,   74,   55,   56,
       80,  181,   46,   57,   46,  126,   75,   58,   59,   81,
      127,   45,   46,   83,   46,   82,   76,   60,  180,   84,

       77,   45,   78,   79,   61,   85,   86,   46,   45,   46,
       62,   87,   88,  165,   89,   45,   45,  143,  166,  179,
       90,   45,   96,   97,   91,   46,   92,  144,   46,   93,
       46,   46,   45,   46,   46,  178,  101,   45,  100,  103,
       45,  177,  106,   45,  104,   46,  105,   46,  107,   46,
      117,  108,  176,  118,   45,  114,  115,  119,   45,  175,
      120,  116,  133,  145,  134,  135,  136,  168,  137,  138,
       46,  169,   46,  146,   46,   46,   46,   46,   46,   45,
       46,  174,  173,   45,   45,  172,   46,   45,   46,  153,
       46,   46,   46,   46,  171,   45,  170,  167,  164,   45,

       45,  163,  162,  161,  160,  159,  158,  157,  154,   40,
      156,   40,   40,   41,   41,   41,   41,   45,   45,  155,
      152,  151,  150,  149,  148,  147,  142,  141,  140,  139,
      130,  129,  128,  125,  124,  123,  113,  112,  111,  110,
      109,  102,   99,   98,   42,   95,   39,   37,   94,   72,
       44,   43,   42,   39,   37,  184,    3,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184

    } ;

static yyconst short int yy_chk[297] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   19,
       72,   27,   25,   27,  185,   72,   19,   19,   19,   19,
       19,   19,   25,   20,   20,   24,   20,  182,   19,   20,
       26,   26,   24,   20,   21,  180,   21,   21,   24,   21,
       26,   26,   83,   83,   21,   30,   21,   30,   21,   22,
       32,  179,   22,   22,   22,   78,   30,   22,   22,   32,
       78,   22,   23,   33,   23,   32,   30,   23,  178,   33,

       31,   23,   31,   31,   23,   33,   33,   48,   46,   48,
       23,   34,   34,  128,   34,   46,   48,   90,  128,  177,
       34,   46,   47,   47,   34,   47,   34,   90,   50,   34,
       50,   52,   47,   52,   53,  176,   53,   50,   52,   55,
       52,  175,   56,   53,   55,   56,   55,   56,   57,   57,
       68,   57,  174,   68,   56,   67,   67,   69,   57,  173,
       69,   67,   84,   92,   84,   84,   85,  132,   85,   85,
       96,  132,   96,   92,   97,  101,   97,  101,  106,   96,
      106,  172,  157,   97,  101,  150,  107,  106,  107,  108,
      153,  108,  153,  108,  137,  107,  134,  130,  127,  153,

      108,  126,  122,  121,  116,  115,  113,  112,  108,  186,
      110,  186,  186,  187,  187,  187,  187,  188,  188,  109,
      104,  103,  102,  100,   94,   93,   89,   88,   87,   86,
       82,   81,   79,   77,   75,   74,   64,   63,   62,   61,
       59,   54,   51,   49,   41,   40,   39,   37,   35,   28,
       15,   14,   13,    8,    5,    3,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "asm.l"
#define INITIAL 0
/* flex input file for WinZ80 debugger scanner */
#line 4 "asm.l"

#define ERROR_TOK -1

#define YY_ALWAYS_INTERACTIVE 1
#line 562 "asm-lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 14 "asm.l"


#line 712 "asm-lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 185 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 257 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 16 "asm.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "asm.l"
{ return '\n'; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "asm.l"
{ return '\n'; /* ignore comments */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "asm.l"
{ return DEFBT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "asm.l"
{ return DEFWT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "asm.l"
{ return EQUT;  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "asm.l"
{ return EQUAT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "asm.l"
{ return ORGT;  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "asm.l"
{ return CLEARLABELST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "asm.l"
{ return FIXLABELST;   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "asm.l"
{ return ADCT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "asm.l"
{ return ADDT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "asm.l"
{ return ANDT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "asm.l"
{ return BITT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "asm.l"
{ return CCFT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "asm.l"
{ return CPLT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "asm.l"
{ return CALLT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "asm.l"
{ return CPT;  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "asm.l"
{ return DAAT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "asm.l"
{ return DECT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "asm.l"
{ return INCT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 39 "asm.l"
{ return DIT;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 40 "asm.l"
{ return EIT;  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 41 "asm.l"
{ return DJNZT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 42 "asm.l"
{ return EXXT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 43 "asm.l"
{ return HALTT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "asm.l"
{ return IMT;  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "asm.l"
{ return INT;  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "asm.l"
{ return EXT;  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "asm.l"
{ return JPT;  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "asm.l"
{ return JRT;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "asm.l"
{ return ORT;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "asm.l"
{ return OUTT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "asm.l"
{ return LDT;  }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "asm.l"
{ return PUSHT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "asm.l"
{ return POPT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "asm.l"
{ return REST; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "asm.l"
{ return SETT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 56 "asm.l"
{ return RLT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "asm.l"
{ return RRT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "asm.l"
{ return RLCT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "asm.l"
{ return RRCT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "asm.l"
{ return SLAT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 61 "asm.l"
{ return SRAT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 62 "asm.l"
{ return SRLT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "asm.l"
{ return SLLT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "asm.l"
{ return XORT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "asm.l"
{ return SBCT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "asm.l"
{ return SUBT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "asm.l"
{ return RLCAT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 68 "asm.l"
{ return RLAT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 69 "asm.l"
{ return RLDT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 70 "asm.l"
{ return RRAT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "asm.l"
{ return RRCAT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "asm.l"
{ return RRDT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "asm.l"
{ return SCFT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "asm.l"
{ return LDDT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "asm.l"
{ return LDDRT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "asm.l"
{ return LDIT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "asm.l"
{ return LDIRT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "asm.l"
{ return NEGT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "asm.l"
{ return NOPT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "asm.l"
{ return INDT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "asm.l"
{ return INDRT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "asm.l"
{ return INIT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "asm.l"
{ return INIRT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "asm.l"
{ return CPDT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "asm.l"
{ return CPDRT;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 86 "asm.l"
{ return CPIT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 87 "asm.l"
{ return CPIRT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 88 "asm.l"
{ return OTIRT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 89 "asm.l"
{ return OTDRT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 90 "asm.l"
{ return OUTIT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 91 "asm.l"
{ return OUTDT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 92 "asm.l"
{ return RSTT;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 93 "asm.l"
{ return RETIT;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 94 "asm.l"
{ return RETNT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 95 "asm.l"
{ return RETT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 97 "asm.l"
{ return NZT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 98 "asm.l"
{ return ZT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 99 "asm.l"
{ return NCT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 101 "asm.l"
{ return POT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 102 "asm.l"
{ return PET; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 103 "asm.l"
{ return PT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 104 "asm.l"
{ return MT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 106 "asm.l"
{ return yytext[0]; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 107 "asm.l"
{ return '['; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 108 "asm.l"
{ return ']'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 109 "asm.l"
{ return '-'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 110 "asm.l"
{ return TWEELINKS; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 111 "asm.l"
{ return TWEERECHTS; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 113 "asm.l"
{ return REGA; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 114 "asm.l"
{ return REGB; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 115 "asm.l"
{ return REGC; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 116 "asm.l"
{ return REGD; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 117 "asm.l"
{ return REGE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 118 "asm.l"
{ return REGH; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 119 "asm.l"
{ return REGL; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 120 "asm.l"
{ return REGR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 121 "asm.l"
{ return REGI; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 122 "asm.l"
{ return REGIXH; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 123 "asm.l"
{ return REGIXL; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 124 "asm.l"
{ return REGIYH; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 125 "asm.l"
{ return REGIYL; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 127 "asm.l"
{ return REGBC; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 128 "asm.l"
{ return REGDE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 129 "asm.l"
{ return REGHL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 130 "asm.l"
{ return REGSP; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 131 "asm.l"
{ return REGIX; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 132 "asm.l"
{ return REGIY; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 133 "asm.l"
{ return REGAF; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 135 "asm.l"
{ sscanf(yytext+(*yytext=='#'),"%lx",&yylval.arg.n);
                     return NUM; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 138 "asm.l"
{ sscanf(yytext+1,"%ld",&yylval.arg.n);
                     return NUM; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 141 "asm.l"
{ yylval.arg.n = CUR_PC;
                     return NUM; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 144 "asm.l"
{ yylval.arg.n = yytext[1];
                     return NUM; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 147 "asm.l"
{ Ident *id;
                           int i = GetIdIndex(yytext);
                           if (i == -1) {
                             i = AddTempString(yytext);
                           }
                           yylval.id.index = i;
                           id = GetIdent(i);
                           if ((id->type & ~LBL_PERMMASK) == LBL_UNDEF) {
                             yylval.id.type = LBL_UNDEF;
                             return LABEL_UNDEF;
                           } else {
                             yylval.id.type = LBL_VAL;
                             if ((id->type & ~LBL_PERMMASK) == LBL_VAL)
                               yylval.id.val = id->value;
                             else
                               /* LBL_ADDR of LBL_PERMADDR */
                               yylval.id.val = 
                                 Addr2Word(id->value,id->bank,CUR_PC);
                           }
                           return LABEL;
                         }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 169 "asm.l"
{ return ERROR_TOK; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 171 "asm.l"
{ return '\n'; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 173 "asm.l"
ECHO;
	YY_BREAK
#line 1421 "asm-lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 185 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 185 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 184);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 173 "asm.l"


    





